### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by ghost** [mohamad-supangat/binance-auto#1]
status - get balance, symbol price, future position
orders - get all open orders

![image](https://github.com/mohamad-supangat/binance-auto/assets/71973368/139cc513-3d09-4cd2-952a-d382a85294e3)
![image](https://github.com/mohamad-supangat/binance-auto/assets/71973368/43fae8db-c9e7-4f8a-a550-3a38e8c9501d)

**Comment by mohamad-supangat** [comment]
your time is not sync with internet time @MrShadowDev you can use ntp to sync it

**Comment by mohamad-supangat** [comment]
may be this wile help you @MrShadowDev 
windows: 
https://answers.microsoft.com/en-us/windows/forum/all/how-to-force-windows-10-time-to-synch-with-a-time/20f3b546-af38-42fb-a2d0-d4df13cc8f43

in linux:
https://linuxhint.com/sync-time-ntp-server-linux/

**Comment by ghost** [comment]
k ty
